### ISSUE TITLE
Telework Guide, Vancouver: Update the screenshot and instructions for default form view

### ISSUE THREAD

**Issue by roxlam** [CreatorWorkflowsNow/creatorworkflowsnow.github.io#145]
Section 1.5. -- The default form view has the following fields in addition to the ones currently outlined in the guide: Configuration item, Parent, Active. The screenshot needs to be updated to reflect the correct default fields for the form. Then instructions need to be added for the above fields to be removed. Otherwise, I guarantee that it will create confusion with citizen developers.

https://creatorworkflowsnow.github.io/labs/telework-vancouver-101/1.0-Build-the-Foundation/configure-telework-form

**Comment by dalestubblefield** [comment]
I think this is fixed now.

**Comment by dalestubblefield** [comment]
@roxlam Can you check the live site and confirm?

**Comment by dalestubblefield** [comment]
@roxlam confirmed this has been fixed.

**Comment by roxlam** [comment]
Closing this.
