### ISSUE TITLE
one error when importing the telework app's 1.0.2 update set

### ISSUE THREAD

**Issue by MarcMouries** [CreatorWorkflowsNow/creatorworkflowsnow.github.io#162]
See step 6 of https://creatorworkflowsnow.github.io/labs/telework-201_vancouver/Introduction/Import-App

**Comment by dalestubblefield** [comment]
@MarcMouries I think this is working now. Can you test?

**Comment by dalestubblefield** [comment]
@MarcMouries can you check this one?

**Comment by MarcMouries** [comment]
The latest version imported fine with no error. I updated the lab.
